### ISSUE TITLE
No noticeboard showing on Moodle 2.8

### ISSUE THREAD

**Issue by hobbesjaap** [gjb2048/moodle-format_noticebd#1]
Dear Gareth,

Many thanks for all your hard work on this course format. Our school Moodle is version 2.8 and I run into the issue that the noticeboard is only visible when I'm editing the page. As soon as I switch this off, the noticeboard disappears. Is there an easy edit I can make to the code to fix this?

Many thanks in advance!

**Comment by gjb2048** [comment]
Hi,

Sounds like a fault at your end.  If you'd like my support then I offer competitive rates.

Kind regards,

Gareth

**Comment by hobbesjaap** [comment]
Hi Gareth,

I figured what I had to do. Enable editing, add a Label to the noticeboard-section, and then things did appear. So I’m not sure it’s a fault on my end, since all other parts of our Moodle are running completely OK, but then, Moodle can be fickle sometimes!

Regards,

Jaap

**Comment by gjb2048** [comment]
Cannot replicate.
